language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
script:
 - dotnet restore
 - dotnet build
 - dotnet test PartyData.UnitTests/PartyData.UnitTests.csproj
 - dotnet test WebApplicationParty.UnitTests/WebApplicationParty.UnitTests.csproj